%WHEN RUNNING THE SIMULATION TASK1 AND ANALYSING THE PICTURE, REMEMBER THAT
%THE CUBE IS TRANSPARENT IN THIS CASE. TRY TO IMAGINE IT AS IF IT WAS
%OPAQUE. IF YOU RUN THE CODE AND THERE ARE TWO FACES OF THE CUBE ONE INSIDE
%THE OTHER, REMEMBER THAT THE BIGGEST ONE IS CLOSER TO YOU, AND IF THE CUBE
%WAS OPAQUE YOU WOULD NOT SEE THE SECOND SMALLER ONE. TRY TO IMAGINE THE
%CUBE AS IF IT WAS OPAQUE AND YOU WILL SEE THAT IT RELATES PERFECTLY WITH
%OUR REALITY AND HOW WE SEE OBJECTS IN THE REAL WORLD.